"""refactoring data types and license

Revision ID: 08e874786014
Revises: 6574d3e2e1fd
Create Date: 2018-12-12 21:17:46.700944

"""

# revision identifiers, used by Alembic.
revision = '08e874786014'
down_revision = '6574d3e2e1fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lambdas', sa.Column('ttype', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lambdas', 'ttype')
    # ### end Alembic commands ###
