"""position revisions

Revision ID: 87081d225807
Revises: cc8d01a1af42
Create Date: 2018-12-19 18:09:43.952776

"""

# revision identifiers, used by Alembic.
revision = '87081d225807'
down_revision = 'cc8d01a1af42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revisions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('revisions', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revisions', 'position')
    op.drop_column('revisions', 'description')
    # ### end Alembic commands ###
