"""adding initial norm

Revision ID: e295bfa9c8ae
Revises: bddc498dd179
Create Date: 2018-08-08 04:52:52.828797

"""

# revision identifiers, used by Alembic.
revision = 'e295bfa9c8ae'
down_revision = 'bddc498dd179'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lambdas',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.String(length=1000), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('perm', sa.String(length=1024), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('dtype', sa.String(length=16), nullable=True),
    sa.Column('shape', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lambda_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lambda_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lambda_id'], ['lambdas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variables',
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('attribute', sa.String(length=256), nullable=True),
    sa.Column('as_input', sa.Boolean(), nullable=True),
    sa.Column('as_output', sa.Boolean(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['lambdas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lambda_variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lambda_id', sa.Integer(), nullable=True),
    sa.Column('variable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lambda_id'], ['lambdas.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lambda_variable')
    op.drop_table('variables')
    op.drop_table('lambda_user')
    op.drop_table('lambdas')
    # ### end Alembic commands ###
