"""change to many-one mapping between revision and lambda

Revision ID: e809b7eb2bcc
Revises: 08e874786014
Create Date: 2018-12-13 18:30:31.246671

"""

# revision identifiers, used by Alembic.
revision = 'e809b7eb2bcc'
down_revision = '08e874786014'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lambda_revision')
    op.add_column('revisions', sa.Column('lambda_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'revisions', 'lambdas', ['lambda_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revisions', type_='foreignkey')
    op.drop_column('revisions', 'lambda_id')
    op.create_table('lambda_revision',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lambda_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revision_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lambda_id'], ['lambdas.id'], name='lambda_revision_lambda_id_fkey'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], name='lambda_revision_revision_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lambda_revision_pkey')
    )
    # ### end Alembic commands ###
