version: '3'
services:
  redis:
    image: redis:4.0.10
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  supernorm:
    image: supernorm
    restart: always
    environment:
      SUPERSET_CONFIG_PATH: /home/work/supernorm/supernorm_config.py
      MYSQL_DB: superset
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SUPERSET_ENV: local
    ports:
      - 8088:8088
    command: "tail -f /dev/null"
    network_mode: host
    depends_on:
      - redis
    volumes:
      - .:/home/work/supernorm
      - superset-node-modules:/home/work/supernorm/superset/assets/node_modules
volumes:
  redis:
    external: false
  superset-node-modules:
    external: false
