version: '3'
services:
  redis:
    image: redis:4.0.10
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:10.4
    restart: always
    user: root
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  npm-build:
    image: supernorm
    volumes:
      - .:/home/work/supernorm
      - superset-node-modules:/home/work/supernorm/superset/assets/node_modules
      - superset-dist:/home/work/supernorm/superset/assets/dist
    command: ["/bin/bash", "npm-build.sh"]
  supernorm:
    image: supernorm
    restart: always
    environment:
      SUPERSET_CONFIG_PATH: /home/work/supernorm/supernorm_config.py
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SUPERSET_ENV: local
    ports:
      - 8088:8088
    # command: ["/bin/bash", "supernorm-ui-serve.sh"]
    command: "tail -f /dev/null"   # To stay awake for db operations and etc.
    depends_on:
      - redis
      - postgres
      - npm-build
    volumes:
      - .:/home/work/supernorm
      - superset-node-modules:/home/work/supernorm/superset/assets/node_modules
      - superset-dist:/home/work/supernorm/superset/assets/dist
volumes:
  postgres-data:
    external: true
  redis-data:
    external: false
  superset-node-modules:
    external: false
  superset-dist:
    external: true

